credentials:
  usernames:
    admin:
      email: admin@thales-group.com
      name: System Administrator
      password: "$2b$12$83fSDrTkUxNTOyRLtxavquzKh50wz963sbaVtcPgFNfFJmOqGe1N2" # admin_password
cookie:
  expiry_days: 30
  key: random_signature_key_9df2a
  name: thales_mfg_auth_cookie
preauthorized:
  emails: []
