import React from 'react';
import { Search, FileText, Download, Plus } from 'lucide-react';

const reportData = [
  { name: 'Production Summary May 2024', type: 'Summary', by: 'Admin', date: 'May 20, 2024', size: '2.4 MB' },
  { name: 'Machine Health Report', type: 'Detailed', by: 'Ramesh K.', date: 'May 20, 2024', size: '5.1 MB' },
  { name: 'Maintenance Log Q2', type: 'Summary', by: 'Suresh P.', date: 'May 18, 2024', size: '1.8 MB' },
  { name: 'Energy Consumption Report', type: 'Detailed', by: 'Arjun M.', date: 'May 15, 2024', size: '3.7 MB' },
  { name: 'OEE Analysis Report', type: 'Analytics', by: 'Karthik S.', date: 'May 10, 2024', size: '2.2 MB' },
  { name: 'Quality Report', type: 'Summary', by: 'Vijay R.', date: 'May 08, 2024', size: '1.5 MB' },
  { name: 'Downtime Analysis', type: 'Detailed', by: 'Manoj T.', date: 'May 02, 2024', size: '2.9 MB' },
];

export default function Reports() {
  return (
    <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem' }}>
      
      {/* Top Header */}
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <div>
          <h2 style={{ marginBottom: '5px' }}>Reports</h2>
          <p style={{ fontSize: '0.9rem' }}>Generate and manage reports</p>
        </div>
      </div>

      {/* KPI Cards */}
      <div className="grid-cols-4">
        <div className="card">
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '10px' }}>Total Reports</p>
          <div style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>156</div>
        </div>
        <div className="card">
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '10px' }}>Generated This Month</p>
          <div style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>23</div>
        </div>
        <div className="card">
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '10px' }}>Scheduled Reports</p>
          <div style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>12</div>
        </div>
        <div className="card">
          <p style={{ color: 'var(--text-muted)', fontSize: '0.9rem', marginBottom: '10px' }}>Custom Reports</p>
          <div style={{ fontSize: '2.5rem', fontWeight: 'bold' }}>8</div>
        </div>
      </div>

      {/* Table Container */}
      <div className="card" style={{ flex: 1, padding: 0, overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
        
        {/* Toolbar */}
        <div style={{ padding: '1.5rem', borderBottom: '1px solid var(--border-color)', display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <div style={{ display: 'flex', gap: '15px' }}>
            <div style={{ position: 'relative' }}>
              <Search size={16} style={{ position: 'absolute', left: 10, top: 10, color: 'var(--text-muted)' }} />
              <input type="text" className="input-field" placeholder="Search reports..." style={{ paddingLeft: '35px', width: '250px' }} />
            </div>
            <select className="input-field" style={{ width: '150px' }}><option>All Types</option></select>
            <select className="input-field" style={{ width: '150px' }}><option>This Month</option></select>
          </div>
          
          <button className="btn btn-primary">
            <Plus size={16} /> Generate Report
          </button>
        </div>

        {/* Table */}
        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', textAlign: 'left' }}>
            <thead>
              <tr style={{ background: 'rgba(255,255,255,0.02)', color: 'var(--text-muted)', fontSize: '0.85rem', textTransform: 'uppercase' }}>
                <th style={{ padding: '15px', fontWeight: 600, borderBottom: '1px solid var(--border-color)' }}>Report Name</th>
                <th style={{ padding: '15px', fontWeight: 600, borderBottom: '1px solid var(--border-color)' }}>Type</th>
                <th style={{ padding: '15px', fontWeight: 600, borderBottom: '1px solid var(--border-color)' }}>Generated By</th>
                <th style={{ padding: '15px', fontWeight: 600, borderBottom: '1px solid var(--border-color)' }}>Generated On</th>
                <th style={{ padding: '15px', fontWeight: 600, borderBottom: '1px solid var(--border-color)' }}>Size</th>
                <th style={{ padding: '15px', fontWeight: 600, borderBottom: '1px solid var(--border-color)', textAlign: 'right' }}>Actions</th>
              </tr>
            </thead>
            <tbody>
              {reportData.map((r, i) => (
                <tr key={i} style={{ borderBottom: '1px solid var(--border-color)' }} className="table-row-hover">
                  <td style={{ padding: '15px', fontWeight: 500 }}>
                    <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
                      <FileText size={18} color="var(--primary-neon)" />
                      {r.name}
                    </div>
                  </td>
                  <td style={{ padding: '15px', color: 'var(--text-muted)' }}>{r.type}</td>
                  <td style={{ padding: '15px' }}>{r.by}</td>
                  <td style={{ padding: '15px', color: 'var(--text-muted)' }}>{r.date}</td>
                  <td style={{ padding: '15px', color: 'var(--text-muted)' }}>{r.size}</td>
                  <td style={{ padding: '15px', textAlign: 'right' }}>
                    <button className="btn btn-secondary" style={{ padding: '4px 10px', fontSize: '0.8rem' }}>
                      <Download size={14} /> Download
                    </button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
      
      <style dangerouslySetInnerHTML={{__html: `
        .table-row-hover:hover { background-color: rgba(255,255,255,0.02); }
      `}} />
    </div>
  );
}
